{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5067358d-6de8-4029-bcfa-77a85b4efb8a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b6422f05-b72f-4961-b839-e3351eff6c0b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "==============================\n",
      "Task 1 - Creating Arrays\n",
      "==============================\n",
      "\n",
      "1. 1D Array (1 to 10):\n",
      "[ 1  2  3  4  5  6  7  8  9 10]\n",
      "\n",
      "2. 2D Array (3*3):\n",
      "[[1 2 3]\n",
      " [4 5 6]\n",
      " [7 8 9]]\n",
      "\n",
      "3. 3D Array (4*4):\n",
      "[[0. 0. 0. 0.]\n",
      " [0. 0. 0. 0.]\n",
      " [0. 0. 0. 0.]\n",
      " [0. 0. 0. 0.]]\n",
      "\n",
      "4. Ones Array (2*5):\n",
      "[[1. 1. 1. 1. 1.]\n",
      " [1. 1. 1. 1. 1.]]\n"
     ]
    }
   ],
   "source": [
    "print(\"=\" * 30)\n",
    "print(\"Task 1 - Creating Arrays\")\n",
    "print(\"=\" * 30)\n",
    "array_1d = np.arange(1, 11)\n",
    "print(\"\\n1. 1D Array (1 to 10):\")\n",
    "print(array_1d)\n",
    "array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])\n",
    "print(\"\\n2. 2D Array (3*3):\")\n",
    "print(array_2d)\n",
    "zeros_array = np.zeros((4,4))\n",
    "print(\"\\n3. 3D Array (4*4):\")\n",
    "print(zeros_array)\n",
    "ones_array = np.ones((2, 5))\n",
    "print(\"\\n4. Ones Array (2*5):\")\n",
    "print(ones_array)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "00746cea-be1e-437c-9323-742ac52dc227",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==============================\n",
      "Task 2 - Array Properties\n",
      "==============================\n",
      "\n",
      "Sample 2D Array:\n",
      "[[10 20 30]\n",
      " [40 50 60]\n",
      " [70 80 90]]\n",
      "\n",
      "1. Shape of array: (3, 3)\n",
      "2. Total number of elements: 9\n",
      "3. Data type of elements: int64\n",
      "4. Number of dimensions: 2\n",
      "\n",
      "5. Why shape is important in AI:\n",
      ".Shape determine input dimensions for neural networks.\n",
      ".Enables automatic broadcasting and matrix operations.\n",
      ".Crucial for reshaping data for different model architectures.\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 30)\n",
    "print(\"Task 2 - Array Properties\")\n",
    "print(\"=\" * 30)\n",
    "sample_array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])\n",
    "print(\"\\nSample 2D Array:\")\n",
    "print(sample_array)\n",
    "print(f\"\\n1. Shape of array: {sample_array.shape}\")\n",
    "print(f\"2. Total number of elements: {sample_array.size}\")\n",
    "print(f\"3. Data type of elements: {sample_array.dtype}\")\n",
    "print(f\"4. Number of dimensions: {sample_array.ndim}\")\n",
    "print(\"\\n5. Why shape is important in AI:\")\n",
    "print(\".Shape determine input dimensions for neural networks.\")\n",
    "print(\".Enables automatic broadcasting and matrix operations.\")\n",
    "print(\".Crucial for reshaping data for different model architectures.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "b65c64a9-40df-4d8a-828a-b70bdfb2bbf8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==============================\n",
      "Task 3 - Indexing\n",
      "==============================\n",
      "\n",
      "1. Array: [10 20 30 40 50 60]\n",
      "\n",
      "2. First element (index 0): 10\n",
      "   Last element (index -1): 60\n",
      "   Third element (index 2): 30\n",
      "\n",
      "3. All values greater than 30: [40 50 60]\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 30)\n",
    "print(\"Task 3 - Indexing\")\n",
    "print(\"=\" * 30)\n",
    "array_indexing = np.array([10, 20, 30, 40, 50, 60])\n",
    "print(f\"\\n1. Array: {array_indexing}\")\n",
    "print(f\"\\n2. First element (index 0): {array_indexing[0]}\")\n",
    "print(f\"   Last element (index -1): {array_indexing[-1]}\")\n",
    "print(f\"   Third element (index 2): {array_indexing[2]}\")\n",
    "values_gt_30 = array_indexing[array_indexing > 30]\n",
    "print(f\"\\n3. All values greater than 30: {values_gt_30}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "443b7ae9-becc-4313-b996-993a6943b4d2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==============================\n",
      "Task 4 - Slicing\n",
      "==============================\n",
      "\n",
      "Original array: [10 20 30 40 50 60]\n",
      "\n",
      "1. Elements from index 1 to 4 (array[1:5]): [20 30 40 50]\n",
      "2. Reversed array (array[::-1]): [60 50 40 30 20 10]\n",
      "3. Alternate elements (array[::2]): [10 30 50]\n",
      "\n",
      "4. 3×3 Matrix:\n",
      "[[1 2 3]\n",
      " [4 5 6]\n",
      " [7 8 9]]\n",
      "   First row: [1 2 3]\n",
      "   Second column: [2 5 8]\n",
      "   Last two rows: [[4 5 6]\n",
      " [7 8 9]]\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 30)\n",
    "print(\"Task 4 - Slicing\")\n",
    "print(\"=\" * 30)\n",
    "array_slicing = np.array([10, 20, 30, 40, 50, 60])\n",
    "print(f\"\\nOriginal array: {array_slicing}\")\n",
    "slice_1_4 = array_slicing[1:5]\n",
    "print(f\"\\n1. Elements from index 1 to 4 (array[1:5]): {slice_1_4}\")\n",
    "reversed_array = array_slicing[::-1]\n",
    "print(f\"2. Reversed array (array[::-1]): {reversed_array}\")\n",
    "alternate = array_slicing[::2]\n",
    "print(f\"3. Alternate elements (array[::2]): {alternate}\")\n",
    "matrix_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])\n",
    "print(f\"\\n4. 3×3 Matrix:\")\n",
    "print(matrix_3x3)\n",
    "print(f\"   First row: {matrix_3x3[0]}\")\n",
    "print(f\"   Second column: {matrix_3x3[:, 1]}\")\n",
    "print(f\"   Last two rows: {matrix_3x3[-2:]}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "3136c95a-41a2-4b07-847c-7196a5f4bf59",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==============================\n",
      "Task 5 - Vectorization\n",
      "==============================\n",
      "\n",
      "1. Original array: [1 2 3 4 5]\n",
      "2. Multiply by 5: [ 5 10 15 20 25]\n",
      "3. Add 10: [11 12 13 14 15]\n",
      "4. Square all elements: [ 1  4  9 16 25]\n",
      "\n",
      "5. Why vectorization is important in AI?\n",
      ".Vectorization is 100-100x faster than loops in python.\n",
      ".NumPy uses optimized C code for element-wise operations.\n",
      ".GPU acceleration works on vectorized operations.\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 30)\n",
    "print(\"Task 5 - Vectorization\")\n",
    "print(\"=\" * 30)\n",
    "vec_array = np.array([1, 2, 3, 4, 5])\n",
    "print(f\"\\n1. Original array: {vec_array}\")\n",
    "multiplied = vec_array * 5\n",
    "print(f\"2. Multiply by 5: {multiplied}\")\n",
    "added = vec_array + 10\n",
    "print(f\"3. Add 10: {added}\")\n",
    "squared = vec_array ** 2\n",
    "print(f\"4. Square all elements: {squared}\")\n",
    "print(\"\\n5. Why vectorization is important in AI?\")\n",
    "print(\".Vectorization is 100-100x faster than loops in python.\")\n",
    "print(\".NumPy uses optimized C code for element-wise operations.\")\n",
    "print(\".GPU acceleration works on vectorized operations.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "ffd574b2-7b62-4c71-a245-d8905de397fb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==============================\n",
      "Task 6 - Broadcasting\n",
      "==============================\n",
      "\n",
      "1. Original 2×3 array:\n",
      "[[1 2 3]\n",
      " [4 5 6]]\n",
      "\n",
      "2. Add 10 to all elements:\n",
      "[[11 12 13]\n",
      " [14 15 16]]\n",
      "\n",
      "3. Multiply entire array by 2:\n",
      "[[ 2  4  6]\n",
      " [ 8 10 12]]\n",
      "\n",
      "4. How broadcasting helps in machine learning?\n",
      ".Enables opertions on different- shaped arrays.\n",
      ".Eliminates need for explicit loops.\n",
      ".Reduces memory usage and computation time.\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 30)\n",
    "print(\"Task 6 - Broadcasting\")\n",
    "print(\"=\" * 30)\n",
    "broadcast_array = np.array([[1, 2, 3], [4, 5, 6]])\n",
    "print(f\"\\n1. Original 2×3 array:\")\n",
    "print(broadcast_array)\n",
    "added_broadcast = broadcast_array + 10\n",
    "print(f\"\\n2. Add 10 to all elements:\")\n",
    "print(added_broadcast)\n",
    "multiplied_broadcast = broadcast_array * 2\n",
    "print(f\"\\n3. Multiply entire array by 2:\")\n",
    "print(multiplied_broadcast)\n",
    "print(\"\\n4. How broadcasting helps in machine learning?\")\n",
    "print(\".Enables opertions on different- shaped arrays.\")\n",
    "print(\".Eliminates need for explicit loops.\")\n",
    "print(\".Reduces memory usage and computation time.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "011d3be2-b3cf-46a8-b790-fd0ee8ccb092",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "========================================\n",
      "Task 7 - Matrix Addition And Subtraction\n",
      "========================================\n",
      "\n",
      "Matrix A:\n",
      "[[1 2]\n",
      " [3 4]]\n",
      "\n",
      "Matrix B:\n",
      "[[5 6]\n",
      " [7 8]]\n",
      "\n",
      "1. Addition (A + B):\n",
      "[[ 6  8]\n",
      " [10 12]]\n",
      "\n",
      "2. Subtraction (A - B):\n",
      "[[-4 -4]\n",
      " [-4 -4]]\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 40)\n",
    "print(\"Task 7 - Matrix Addition And Subtraction\")\n",
    "print(\"=\" * 40)\n",
    "matrix_a = np.array([[1, 2], [3, 4]])\n",
    "matrix_b = np.array([[5, 6], [7, 8]])\n",
    "print(f\"\\nMatrix A:\")\n",
    "print(matrix_a)\n",
    "print(f\"\\nMatrix B:\")\n",
    "print(matrix_b)\n",
    "addition = matrix_a + matrix_b\n",
    "subtraction = matrix_a - matrix_b\n",
    "print(f\"\\n1. Addition (A + B):\")\n",
    "print(addition)\n",
    "print(f\"\\n2. Subtraction (A - B):\")\n",
    "print(subtraction)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "bfd8805e-86b6-4ffe-bb9a-2f24d344633c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==============================\n",
      "Task 8 - Matrix Multiplication\n",
      "==============================\n",
      "\n",
      "Matrix 1:\n",
      "[[1 2]\n",
      " [3 4]]\n",
      "\n",
      "Matrix 2:\n",
      "[[5 6]\n",
      " [7 8]]\n",
      "\n",
      "1. Matrix multiplication using np.dot():\n",
      "[[19 22]\n",
      " [43 50]]\n",
      "\n",
      "2. Transpose of Matrix 1:\n",
      "[[1 3]\n",
      " [2 4]]\n",
      "\n",
      "3. Relation of matrix multiplication with neural networks:\n",
      ".Weights are stored as matrices.\n",
      ".Convolution operations use matrix multiplication.\n",
      ".Attention mechanisms use matrix multiplication.\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 30)\n",
    "print(\"Task 8 - Matrix Multiplication\")\n",
    "print(\"=\" * 30)\n",
    "mat1 = np.array([[1, 2], [3, 4]])\n",
    "mat2 = np.array([[5, 6], [7, 8]])\n",
    "print(f\"\\nMatrix 1:\")\n",
    "print(mat1)\n",
    "print(f\"\\nMatrix 2:\")\n",
    "print(mat2)\n",
    "dot_product = np.dot(mat1, mat2)\n",
    "print(f\"\\n1. Matrix multiplication using np.dot():\")\n",
    "print(dot_product)\n",
    "transpose_mat1 = mat1.T\n",
    "print(f\"\\n2. Transpose of Matrix 1:\")\n",
    "print(transpose_mat1)\n",
    "print(\"\\n3. Relation of matrix multiplication with neural networks:\")\n",
    "print(\".Weights are stored as matrices.\")\n",
    "print(\".Convolution operations use matrix multiplication.\")\n",
    "print(\".Attention mechanisms use matrix multiplication.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "f97a5f9d-bc16-47aa-b852-dcb62628a43f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=========================\n",
      "Task 9 - Random Arrays\n",
      "=========================\n",
      "\n",
      "1. Random integer array (4×4) between 1-100:\n",
      "[[ 52  93  15  72]\n",
      " [ 61  21  83  87]\n",
      " [ 75  75  88 100]\n",
      " [ 24   3  22  53]]\n",
      "\n",
      "2. Random decimal values (3×3) between 0-1:\n",
      "[[0.96990985 0.83244264 0.21233911]\n",
      " [0.18182497 0.18340451 0.30424224]\n",
      " [0.52475643 0.43194502 0.29122914]]\n",
      "\n",
      "3. Statistics from random integer array:\n",
      "   Maximum value: 100\n",
      "   Minimum value: 3\n",
      "   Average value: 57.75\n",
      "\n",
      "4. Why random numbers are important in AI?\n",
      ".Weight initialization in neural networks.\n",
      ".Data shuffling and batch sampling.\n",
      ".Exploration in Reinforcement Learning.\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 25)\n",
    "print(\"Task 9 - Random Arrays\")\n",
    "print(\"=\" * 25)\n",
    "np.random.seed(42)\n",
    "random_int = np.random.randint(1, 101, size=(4, 4))\n",
    "print(f\"\\n1. Random integer array (4×4) between 1-100:\")\n",
    "print(random_int)\n",
    "random_decimal = np.random.rand(3, 3)\n",
    "print(f\"\\n2. Random decimal values (3×3) between 0-1:\")\n",
    "print(random_decimal)\n",
    "print(f\"\\n3. Statistics from random integer array:\")\n",
    "print(f\"   Maximum value: {random_int.max()}\")\n",
    "print(f\"   Minimum value: {random_int.min()}\")\n",
    "print(f\"   Average value: {random_int.mean():.2f}\")\n",
    "print(\"\\n4. Why random numbers are important in AI?\")\n",
    "print(\".Weight initialization in neural networks.\")\n",
    "print(\".Data shuffling and batch sampling.\")\n",
    "print(\".Exploration in Reinforcement Learning.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "b7a3942e-4fbb-4689-b198-5360e2aa4a13",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "===================================\n",
      "Task 10 - Student Marks Analysis\n",
      "===================================\n",
      "\n",
      "1. Student Marks (10 students): [92 78 85 45 88 76 95 62 81 55]\n",
      "\n",
      "2. Statistics:\n",
      "   Average marks: 75.70\n",
      "   Highest marks: 95\n",
      "   Lowest marks: 45\n",
      "\n",
      "3. Students who scored above 80: 5\n",
      "\n",
      "4. Students who failed (below 50): [45]\n",
      "\n",
      "5. Number of students who failed: 1\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 35)\n",
    "print(\"Task 10 - Student Marks Analysis\")\n",
    "print(\"=\" * 35)\n",
    "marks = np.array([92, 78, 85, 45, 88, 76, 95, 62, 81, 55])\n",
    "print(f\"\\n1. Student Marks (10 students): {marks}\")\n",
    "average_marks = marks.mean()\n",
    "highest_marks = marks.max()\n",
    "lowest_marks = marks.min()\n",
    "print(f\"\\n2. Statistics:\")\n",
    "print(f\"   Average marks: {average_marks:.2f}\")\n",
    "print(f\"   Highest marks: {highest_marks}\")\n",
    "print(f\"   Lowest marks: {lowest_marks}\")\n",
    "above_80 = (marks > 80).sum()\n",
    "print(f\"\\n3. Students who scored above 80: {above_80}\")\n",
    "failed_students = marks[marks < 50]\n",
    "print(f\"\\n4. Students who failed (below 50): {failed_students}\")\n",
    "print(f\"\\n5. Number of students who failed: {len(failed_students)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "591a2118-1704-4912-8f15-92378b30a7d5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "===================================\n",
      "Task 11 - Image Pixel Simulation\n",
      "===================================\n",
      "\n",
      "1. Random 5×5 image pixel array (0-255):\n",
      "[[102 179  92  14 106]\n",
      " [ 71 188  20 102 121]\n",
      " [210 214  74 202  87]\n",
      " [116  99 103 151 130]\n",
      " [149  52   1  87 235]]\n",
      "\n",
      "2. Image Analysis:\n",
      "   Brightest pixel value: 235\n",
      "   Darkest pixel value: 1\n",
      "   Shape of image: (5, 5)\n",
      "\n",
      "3. How AI reads images using arrays?\n",
      ".Images are represented as 2D arrays (grayscale) or 3D arrays (RGB.)\n",
      ".Grayscale: (height, width) with values 0-255.\n",
      ".Efficient array operations allow real-time image processing.\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 35)\n",
    "print(\"Task 11 - Image Pixel Simulation\")\n",
    "print(\"=\" * 35)\n",
    "np.random.seed(42)\n",
    "image_pixels = np.random.randint(0, 256, size=(5, 5))\n",
    "print(f\"\\n1. Random 5×5 image pixel array (0-255):\")\n",
    "print(image_pixels)\n",
    "brightest = image_pixels.max()\n",
    "darkest = image_pixels.min()\n",
    "shape = image_pixels.shape\n",
    "print(f\"\\n2. Image Analysis:\")\n",
    "print(f\"   Brightest pixel value: {brightest}\")\n",
    "print(f\"   Darkest pixel value: {darkest}\")\n",
    "print(f\"   Shape of image: {shape}\")\n",
    "print(\"\\n3. How AI reads images using arrays?\")\n",
    "print(\".Images are represented as 2D arrays (grayscale) or 3D arrays (RGB.)\")\n",
    "print(\".Grayscale: (height, width) with values 0-255.\")\n",
    "print(\".Efficient array operations allow real-time image processing.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "97b8b968-f106-45e7-b6fe-42dcb8fe7e42",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==============================\n",
      "Task 12 - Data Normalization\n",
      "==============================\n",
      "\n",
      "1. Original data: [ 10  20  30  40  50  60  70  80  90 100]\n",
      "\n",
      "2. Normalization formula: (x - min) / (max - min)\n",
      "   Min value: 10\n",
      "   Max value: 100\n",
      "   Normalized values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556\n",
      " 0.66666667 0.77777778 0.88888889 1.        ]\n",
      "\n",
      "3. Normalized data (values between 0 and 1):\n",
      "   Original:  10 → Normalized: 0.0000\n",
      "   Original:  20 → Normalized: 0.1111\n",
      "   Original:  30 → Normalized: 0.2222\n",
      "   Original:  40 → Normalized: 0.3333\n",
      "   Original:  50 → Normalized: 0.4444\n",
      "   Original:  60 → Normalized: 0.5556\n",
      "   Original:  70 → Normalized: 0.6667\n",
      "   Original:  80 → Normalized: 0.7778\n",
      "   Original:  90 → Normalized: 0.8889\n",
      "   Original: 100 → Normalized: 1.0000\n",
      "\n",
      "4. Why normalization improves AI model performance?\n",
      ".Scales features to similar ranges (0-1 or -1 to 1).\n",
      ".Prevents features with large ranges from dominating.\n",
      ".Speeds up gradient descent convergence.\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 30)\n",
    "print(\"Task 12 - Data Normalization\")\n",
    "print(\"=\" * 30)\n",
    "data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])\n",
    "print(f\"\\n1. Original data: {data}\")\n",
    "min_val = data.min()\n",
    "max_val = data.max()\n",
    "normalized = (data - min_val) / (max_val - min_val)\n",
    "print(f\"\\n2. Normalization formula: (x - min) / (max - min)\")\n",
    "print(f\"   Min value: {min_val}\")\n",
    "print(f\"   Max value: {max_val}\")\n",
    "print(f\"   Normalized values: {normalized}\")\n",
    "print(f\"\\n3. Normalized data (values between 0 and 1):\")\n",
    "for i, val in enumerate(normalized):\n",
    "    print(f\"   Original: {data[i]:3d} → Normalized: {val:.4f}\")\n",
    "print(\"\\n4. Why normalization improves AI model performance?\")\n",
    "print(\".Scales features to similar ranges (0-1 or -1 to 1).\")\n",
    "print(\".Prevents features with large ranges from dominating.\")\n",
    "print(\".Speeds up gradient descent convergence.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "cb4c6c36-0d18-4faa-a894-dd71f189c97e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==============================\n",
      "Task 13 - Mini AI Dataset Task\n",
      "==============================\n",
      "\n",
      "1. Creating AI Dataset (Age, Salary, Purchased Product):\n",
      "\n",
      "Age: [25 32 45 28 35 50 23 40 29 38]\n",
      "Salary: [30000 45000 75000 35000 55000 85000 28000 70000 40000 60000]\n",
      "Purchased (0=No, 1=Yes): [0 1 1 0 1 1 0 1 0 1]\n",
      "\n",
      "1. Dataset as NumPy array shape (10, 3):\n",
      "[[   25 30000     0]\n",
      " [   32 45000     1]\n",
      " [   45 75000     1]\n",
      " [   28 35000     0]\n",
      " [   35 55000     1]\n",
      " [   50 85000     1]\n",
      " [   23 28000     0]\n",
      " [   40 70000     1]\n",
      " [   29 40000     0]\n",
      " [   38 60000     1]]\n",
      "\n",
      "2. Separated Features (input) shape (10, 2):\n",
      "[[   25 30000]\n",
      " [   32 45000]\n",
      " [   45 75000]\n",
      " [   28 35000]\n",
      " [   35 55000]\n",
      " [   50 85000]\n",
      " [   23 28000]\n",
      " [   40 70000]\n",
      " [   29 40000]\n",
      " [   38 60000]]\n",
      "\n",
      "   Separated Labels (output) shape (10,):\n",
      "[0 1 1 0 1 1 0 1 0 1]\n",
      "\n",
      "3. Average salary: $52,300.00\n",
      "4. Highest age: 50 years\n",
      "\n",
      "5. Dataset shape: (10, 3)\n",
      ".Samples (rows): 10\n",
      ".Features (columns): 3\n",
      "==========THE END========\n"
     ]
    }
   ],
   "source": [
    "print(\"\\n\" + \"=\" * 30)\n",
    "print(\"Task 13 - Mini AI Dataset Task\")\n",
    "print(\"=\" * 30)\n",
    "print(\"\\n1. Creating AI Dataset (Age, Salary, Purchased Product):\")\n",
    "age = np.array([25, 32, 45, 28, 35, 50, 23, 40, 29, 38])\n",
    "salary = np.array([30000, 45000, 75000, 35000, 55000, 85000, 28000, 70000, 40000, 60000])\n",
    "purchased = np.array([0, 1, 1, 0, 1, 1, 0, 1, 0, 1])\n",
    "print(f\"\\nAge: {age}\")\n",
    "print(f\"Salary: {salary}\")\n",
    "print(f\"Purchased (0=No, 1=Yes): {purchased}\")\n",
    "dataset = np.column_stack((age, salary, purchased))\n",
    "print(f\"\\n1. Dataset as NumPy array shape {dataset.shape}:\")\n",
    "print(dataset)\n",
    "features = dataset[:, :2] \n",
    "labels = dataset[:, 2]     \n",
    "print(f\"\\n2. Separated Features (input) shape {features.shape}:\")\n",
    "print(features)\n",
    "print(f\"\\n   Separated Labels (output) shape {labels.shape}:\")\n",
    "print(labels)\n",
    "avg_salary = salary.mean()\n",
    "print(f\"\\n3. Average salary: ${avg_salary:,.2f}\")\n",
    "highest_age = age.max()\n",
    "print(f\"4. Highest age: {highest_age} years\")\n",
    "print(f\"\\n5. Dataset shape: {dataset.shape}\")\n",
    "print(f\".Samples (rows): {dataset.shape[0]}\")\n",
    "print(f\".Features (columns): {dataset.shape[1]}\")\n",
    "\n",
    "print(\"==========THE END========\")\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "84379389-e167-45e8-85d7-e60189917936",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
